language: dart
sudo: required
addons:
  chrome: stable
matrix:
  include:
    - dart: dev
      script:
        - dartanalyzer --fatal-warnings lib/ test/
    - dart: dev
      script:
        - dartfmt --set-exit-if-changed -l 120 -n .
    - dart: dev
      dart_task:
        test: --platform firefox -j 1
    - dart: dev
      dart_task:
        test: --platform chrome
    - dart: dev
      script:
        - pub run dart_codecov_generator --report-on=lib/ --no-html --verbose
        - bash <(curl -s https://codecov.io/bash)
# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]
cache:
  directories:
    - $HOME/.pub-cache
